POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer

{
    "title": "The Solo's Manual",
    "author": "Morgan Blackhand",
    "url": "https://blackhands-fake-blog.org",
    "likes": 2077
}